# <TITLE>

################################################################################
# USAGE


################################################################################
# REFERENCES


################################################################################
################################################################################

define

################
################
## ENTITIES ##
################
################

########################
## <SUB-HEADING> ##
########################

# <title>
# source: <source ontology, [link]>
# elucidation: etc
# editors note: etc

################
################
## ATTRIBUTES ##
################
################

################
################
## RELATIONS ##
################
################

################
################
## RULES ##
################
################
