# Common Core Ontologies
# https://github.com/CommonCoreOntology/CommonCoreOntologies

define

  # http://www.ontologyrepository.com/CommonCoreOntologies/InformationBearingEntity
  # definition "An Object upon which an Information Content Entity
  # generically depends."
  information-bearing-entity sub object;

  # http://www.ontologyrepository.com/CommonCoreOntologies/InformationContentEntity
  # definition "A Generically Dependent Continuant that generically depends on
  # some Information Bearing Entity and stands in relation of aboutness
  # to some Entity."
  # elucidation "Information Content Entity is here intended to be a class
  # of Entities whose instances are the informational content of
  # Information Bearing Entities. For example, three instances of
  # information bearers -- such as a bar chart, color-coded map, and
  # a written report -- each of which lists the GDP of Countries for the
  # year 2010 are each different bearers of the same information content.
  # It is this content that is generically dependent upon its bearer.
  # This treatment of Informational Content Entity (cf. the Information
  # Artifact Ontology) leads to a principle of subtyping based upon the
  # relationship that ICE's have with the Entity they are about rather than
  # characteristics such as format, language, measurement scale, or media.
  # The latter are treated here as being Qualities of bearers."
  information-content-entity sub generically-dependent-continuant;

  # http://www.ontologyrepository.com/CommonCoreOntologies/DescriptiveInformationContentEntity
  # definition "An Information Content Entity that consists of a set of
  # propositions that describe some Entity."^^xsd:string
  descriptive-information-content-entity sub information-content-entity;

  # http://www.ontologyrepository.com/CommonCoreOntologies/MeasurementInformationContentEntity
  # definition "A Descriptive Information Content Entity that describes the
  # extent, dimensions, quantity, or quality of an Entity relative to some
  # standard."^^xsd:string
  measurement-information-content-entity sub descriptive-information-content-entity;

  # TODO: subclasses

  # http://www.ontologyrepository.com/CommonCoreOntologies/MeasurementUnit
  # definition "A Descriptive Information Content Entity that describes a
  # definite magnitude of a physical quantity, defined and adopted by
  # convention and/or by law, that is used as a standard for measurement of
  # the same physical quantity."^^xsd:string
  measurement-unit sub descriptive-information-content-entity;

  # http://www.ontologyrepository.com/CommonCoreOntologies/PredictiveInformationContentEntity
  # rdfs:comment "Since predictions are inherently about not-yet-existant
  # things, the Modal Relation Ontology term 'describes' (i.e. mro:describes)
  # should be used (instead of the standard cco:describes) to relate instances
  # of Predictive Information Content Entity to the entities they are about."
  predictive-information-content-entity sub descriptive-information-content-entity;

  # http://www.ontologyrepository.com/CommonCoreOntologies/ReferenceSystem
  # definition "A Descriptive Information Content Entity that describes
  # a set of standards for organizing and understanding data of
  # the specified type or domain."^^xsd:string
  reference-system sub descriptive-information-content-entity;

  # http://www.ontologyrepository.com/CommonCoreOntologies/RepresentationalInformationContentEntity
  # definition "A Descriptive Information Content Entity that consists of
  # a set of propositions or an image that represents some Entity."^^xsd:string
  representational-information-content-entity sub descriptive-information-content-entity;
  # http://www.ontologyrepository.com/CommonCoreOntologies/DesignativeInformationContentEntity
  # definition "An Information Content Entity that consists of a set of symbols
  # that denote some Entity."^^xsd:string
  designative-information-content-entity sub information-content-entity;

  # http://www.ontologyrepository.com/CommonCoreOntologies/DirectiveInformationContentEntity
  # definition "An Information Content Entity that consists of a set of
  # propositions or images (as in the case of a blueprint) that prescribe
  # some Entity."^^xsd:string
  directive-information-content-entity sub information-content-entity;

  # http://www.ontologyrepository.com/CommonCoreOntologies/InformationStructureEntity
  # definition "A Generically Dependent Continuant that is not
  # an Information Content Entity (ICE) but which is complemented or
  # complementable by some ICE to create another ICE."
  # example_of_usage "a blank page in a document, a cell in a spreadsheet"
  information-structure-entity sub generically-dependent-continuant;

  # http://www.ontologyrepository.com/CommonCoreOntologies/InformationQualityEntity
  # definition "A Quality that concretizes some Information Content Entity."
  # comment "Typically, an IQE will be a complex pattern made up of
  # multiple qualities joined together spatially."
  information-quality-entity sub quality,
    datatype string;
