# <TITLE>

################################################################################
# PURPOSE

################################################################################
# DESCRIPTION

################################################################################
# EXAMPLES

################################################################################
# USAGE

################################################################################
# REFERENCES

################################################################################
# NOTE

################################################################################
# STATUS

################################################################################
################################################################################

define

################
################
## ENTITIES ##
################
################

########################
## <SUB-HEADING> ##
########################

# source: <source ontology, [link]>
# isDefinedBy: <URL>
# elucidation:
# example of usage:
# status:
# revision history:
# notes:
# reference:
# has associated rule:

################
################
## ATTRIBUTES ##
################
################

################
################
## RELATIONS ##
################
################

################
################
## RULES ##
################
################
