# Linear Algebra ontology
# https://homepage.cs.uiowa.edu/~rus/linearAlgebra.pdf

define

#####################################
############ ENTITY-TYPES ###########
#####################################

  
